[[plugins]]
repo =  'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'tweekmonster/braceless.vim'
on_ft = 'python'


[[plugins]]
repo = 'Shougo/deoplete.nvim'
# http://sinshutu-kibotu.hatenablog.jp/entry/2017/01/27/062757
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
if = 'has("nvim")'
on_i = 1

#[[plugins]]
#repo = 'kassio/neoterm'
#if = "has('nvim')"
